// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.wuttke.tinyscrum.domain;

import eu.wuttke.tinyscrum.domain.ProjectFeature;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ProjectFeature_Roo_Configurable {
    
    declare @type: ProjectFeature: @Configurable;
    
}
