package eu.wuttke.tinyscrum.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import eu.wuttke.tinyscrum.domain.Iteration;
import eu.wuttke.tinyscrum.web.TinyScrumApplication;

public class UserStoryView extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Panel pnlComments;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private RichTextArea rtaDescription;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private ComboBox cbRelease;
	@AutoGenerated
	private ComboBox cbFeature;
	@AutoGenerated
	private ComboBox cbIteration;
	@AutoGenerated
	private HorizontalLayout horizontalLayout;
	@AutoGenerated
	private ComboBox cbStatus;
	@AutoGenerated
	private ComboBox cbOwner;
	@AutoGenerated
	private TextField tfTitle;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public UserStoryView(TinyScrumApplication application) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		cbIteration.setContainerDataSource(new BeanItemContainer<Iteration>(Iteration.class, application.loadIterations()));
		cbIteration.setItemCaptionPropertyId("name");
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("700px");
		mainLayout.setHeight("600px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("700px");
		setHeight("600px");
		
		// tfTitle
		tfTitle = new TextField();
		tfTitle.setCaption("Title");
		tfTitle.setImmediate(false);
		tfTitle.setWidth("100.0%");
		tfTitle.setHeight("-1px");
		tfTitle.setRequired(true);
		tfTitle.setSecret(false);
		mainLayout.addComponent(tfTitle);
		
		// horizontalLayout
		horizontalLayout = buildHorizontalLayout();
		mainLayout.addComponent(horizontalLayout);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		// rtaDescription
		rtaDescription = new RichTextArea();
		rtaDescription.setCaption("Description");
		rtaDescription.setImmediate(false);
		rtaDescription.setWidth("100.0%");
		rtaDescription.setHeight("-1px");
		mainLayout.addComponent(rtaDescription);
		
		// pnlComments
		pnlComments = buildPnlComments();
		mainLayout.addComponent(pnlComments);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout() {
		// common part: create layout
		horizontalLayout = new HorizontalLayout();
		horizontalLayout.setImmediate(false);
		horizontalLayout.setWidth("-1px");
		horizontalLayout.setHeight("-1px");
		horizontalLayout.setMargin(false);
		horizontalLayout.setSpacing(true);
		
		// cbOwner
		cbOwner = new ComboBox();
		cbOwner.setCaption("Owner");
		cbOwner.setImmediate(false);
		cbOwner.setWidth("-1px");
		cbOwner.setHeight("-1px");
		horizontalLayout.addComponent(cbOwner);
		
		// cbStatus
		cbStatus = new ComboBox();
		cbStatus.setCaption("Status");
		cbStatus.setImmediate(false);
		cbStatus.setWidth("-1px");
		cbStatus.setHeight("-1px");
		horizontalLayout.addComponent(cbStatus);
		
		return horizontalLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);
		
		// cbIteration
		cbIteration = new ComboBox();
		cbIteration.setCaption("Iteration");
		cbIteration.setImmediate(false);
		cbIteration.setWidth("-1px");
		cbIteration.setHeight("-1px");
		horizontalLayout_1.addComponent(cbIteration);
		
		// cbFeature
		cbFeature = new ComboBox();
		cbFeature.setCaption("Feature");
		cbFeature.setImmediate(false);
		cbFeature.setWidth("-1px");
		cbFeature.setHeight("-1px");
		horizontalLayout_1.addComponent(cbFeature);
		
		// cbRelease
		cbRelease = new ComboBox();
		cbRelease.setCaption("Release");
		cbRelease.setImmediate(false);
		cbRelease.setWidth("-1px");
		cbRelease.setHeight("-1px");
		horizontalLayout_1.addComponent(cbRelease);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private Panel buildPnlComments() {
		// common part: create layout
		pnlComments = new Panel();
		pnlComments.setCaption("Comments");
		pnlComments.setImmediate(false);
		pnlComments.setWidth("100.0%");
		pnlComments.setHeight("150px");
		
		// verticalLayout_1
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.0%");
		verticalLayout_1.setMargin(false);
		pnlComments.setContent(verticalLayout_1);
		
		return pnlComments;
	}

}
